### ISSUE TITLE
转换后的html中多个空格被替换成s

### ISSUE THREAD

**Issue by maMark** [thesadboy/gulp-template2js#1]
index.js里49行： text = text ? text.replace(/[\r\n\t]/gm, '').replace(/'/gm, '\\\'').replace(/\s{2,}/gim, '\s') :  '';
最后一个replace()方法替换多个空格，第二个参数传入的是‘\s’（字符串）。如果使用的是4个空格缩进，这四个空格就被替换成字符‘s’。

**Comment by thesadboy** [comment]
失误了，已经将\s替换成了空格了。。。
